### ISSUE TITLE
[observability] get all alerting secrets based on some pattern matching

### ISSUE THREAD

**Issue by jkleinlercher** [suxess-it/sx-cnp-oss#1158]
currently a team needs to 

- explicitly list the alerting secrets 
- this needs to be uniq over all teams (so they need to explicitly add a teams prefix)
- and also add the "KUBRIX_" prefix to the env variable, which then could confuse people a lot

```
    alerting:
      secrets:
        - KUBRIX_MSTEAMS_WEBHOOK
      contactPoints:
        receivers:
          - uid: kubrix-team
            type: teams
            settings:
              url: ${KUBRIX_KUBRIX_MSTEAMS_WEBHOOK}
            disableResolveMessage: false
```

we should

- fetch all alertings secrets from vault automatically with https://external-secrets.io/latest/guides/getallsecrets/
- add  the teams prefix automatically in the secret
- and then maybe (if it is possible at all) also add the "KUBRIX_" prefix in the receivers setting automatically. I guess this is not possible, so I would be fine if the "KUBRIX_" prefix must be set by the user and we document that. Why do we use the "KUBRIX_" prefix at all? because otherwise the teams could simply override some Grafana env variables
