### ISSUE TITLE
[loki] GrafanaAgent stuck in pending deletion

### ISSUE THREAD

**Issue by jkleinlercher** [suxess-it/sx-cnp-oss#293]
Shutdown-test Job in github action https://github.com/suxess-it/sx-cnp-oss/actions/runs/9785529844/job/27018726355 often shows loki stuck in deletion. Root cause is GrafanaAgent:

```
Group: monitoring.grafana.com
      health:
        message: Pending deletion
        status: Progressing
      kind: GrafanaAgent
      name: sx-loki
      namespace: monitoring
      status: Synced
      version: v1alpha1
```

one possible hint could be https://github.com/grafana/agent/issues/4177
