### ISSUE TITLE
[kargo] create helm chart for app definition, kargo-project and stages

### ISSUE THREAD

**Issue by jkleinlercher** [suxess-it/sx-cnp-oss#73]
maybe we can create a new helm chart where you can define your stages and appname and everything else (apps per stage, kargo-project and stages) gets create automatically.

values:

```
appname: myapp
namespace: myapp
gitops-repo: https://github.com/flalfl
stages:
  - test:
    upstream: warehouse
  - qa:
    upstream: test
  - prod:
    upstream: qa
```

what the helm-chart creates:
* namespaces: myapp-test, myapp-qa, myapp-prod (with default props (e.g. deny-all nw-policy) (or part of apps and creates automatically))
* argocd apps: myapp-test, myapp-qa, myapp-prod
* all kargo objects (project, stages, warehouse, ...) for delivery pipeline

In Backstage we can then create a gitops repo and and application with this helm-chart above and this parent-app then creates the "staging-apps, namespaces and kargo"
